teachers:
  - id: jan.hybs
    students: 
      - id: jan.hybs
      - id: pavel.exner
      - id: jan.brezina
    
  - id: pavel.exner
    students: 
      - id: jan.hybs
      - id: pavel.exner
